### ISSUE TITLE
Error when I deploy the contract

### ISSUE THREAD

**Issue by ShimolinNik** [petrosDemetrakopoulos/ethairballoons-CRUD-API#4]
Could you help me, please?

When I deploy the contract I have this error: 

Contract deployment errorError: Solidity compilation error [{"component":"general","errorCode":"6651","formattedMessage":"TypeError: Data location must be \"memory\" or \"calldata\" for parameter in function, but none was given.\n --> commentContract.sol:19:20:\n |\n19 | \tfunction isRecord(bytes recordAddress) public view returns (bool isRec) {\n | \t ^^^^^^^^^^^^^^^^^^^\n\n","message":"Data location must be \"memory\" or \"calldata\" for parameter in function, but none was given.","severity":"error","sourceLocation":{"end":383,"file":"commentContract.sol","start":364},"type":"TypeError"},{"component":"general","errorCode":"6651","formattedMessage":"TypeError: Data location must be \"memory\" or \"calldata\" for parameter in function, but none was given.\n --> commentContract.sol:28:44:\n |\n28 | \tfunction addRecord(string memory payload, bytes ID) public returns (bool success) {\n | \t ^^^^^^^^\n\n","message":"Data location must be \"memory\" or \"calldata\" for parameter in function, but none was given.","severity":"error","sourceLocation":{"end":691,"file":"commentContract.sol","start":683},"type":"TypeError"},{"component":"general","errorCode":"6651","formattedMessage":"TypeError: Data location must be \"memory\" or \"calldata\" for parameter in function, but none was given.\n --> commentContract.sol:37:21:\n |\n37 | \tfunction getRecord(bytes id) public view returns (string memory payload){\n | \t ^^^^^^^^\n\n","message":"Data location must be \"memory\" or \"calldata\" for parameter in function, but none was given.","severity":"error","sourceLocation":{"end":965,"file":"commentContract.sol","start":957},"type":"TypeError"},{"component":"general","errorCode":"6651","formattedMessage":"TypeError: Data location must be \"memory\" or \"calldata\" for parameter in function, but none was given.\n --> commentContract.sol:42:24:\n |\n42 | \tfunction updateRecord(bytes id, string memory payload) public returns (bool success){\n | \t ^^^^^^^^\n\n","message":"Data location must be \"memory\" or \"calldata\" for parameter in function, but none was given.","severity":"error","sourceLocation":{"end":1143,"file":"commentContract.sol","start":1135},"type":"TypeError"},{"component":"general","errorCode":"6651","formattedMessage":"TypeError: Data location must be \"memory\" or \"calldata\" for parameter in function, but none was given.\n --> commentContract.sol:57:24:\n |\n57 | \tfunction deleteRecord(bytes id) public returns (bool success) {\n | \t ^^^^^^^^\n\n","message":"Data location must be \"memory\" or \"calldata\" for parameter in function, but none was given.","severity":"error","sourceLocation":{"end":1642,"file":"commentContract.sol","start":1634},"type":"TypeError"},{"component":"general","errorCode":"6651","formattedMessage":"TypeError: Data location must be \"storage\", \"memory\" or \"calldata\" for variable, but none was given.\n --> commentContract.sol:60:3:\n |\n60 | \t\tbytes keyToMove = recordsList[recordsList.length-1];\n | \t\t^^^^^^^^^^^^^^^\n\n","message":"Data location must be \"storage\", \"memory\" or \"calldata\" for variable, but none was given.","severity":"error","sourceLocation":{"end":1803,"file":"commentContract.sol","start":1788},"type":"TypeError"}]

Thanks in advence!!!

**Comment by petrosDemetrakopoulos** [comment]
Please be sure that you have started ganache-cli locally **BEFORE** you start the API server.
Also, please state what version of ganache you are using, in order to reproduce it because I currently cannot reproduce it in my setup.

**Comment by ShimolinNik** [comment]
It's running.

Ganache CLI v6.12.2 (ganache-core: 2.13.2)

**Comment by ShimolinNik** [comment]
The contract was created in the /contract folder, but after when I do the operations nothing happens.

**Comment by petrosDemetrakopoulos** [comment]
Please upgrade to ganache v7.0.1 (@ganache/cli: 0.1.2, @ganache/core: 0.1.2). 
It should work fine.

**Comment by ShimolinNik** [comment]
Sorry, could you give me a command? Because as I read now it's not ganache-cli, but just ganache

**Comment by ShimolinNik** [comment]
Now I have this : ganache v7.3.0 (@ganache/cli: 0.4.0, @ganache/core: 0.4.0)
But the same error(
Maybe I can use ganache desktop application?

**Comment by petrosDemetrakopoulos** [comment]
Can you please send me the definition of the Schema that you are using? Probably something is not set correctly there.
I need the JSON /JS Object that you pass as a parameter in the .**createSchema** function.

**Comment by ShimolinNik** [comment]
const Comment = ethAirBalloonsProvider.createSchema({
        name: "Comment",
        contractName: "commentContract",
        properties: [
            {
                name: "articleName",
                type: "bytes",
                primaryKey: true
            },
            {
                name: "articleText",
                type: "bytes32",
            },
            {   name: "comment",
                type: "bytes"
            }
        ]
    });

**Comment by petrosDemetrakopoulos** [comment]
The issue is that the number of the bytes in Solidity must be explicitly set. So just change "bytes" to "bytes32" for the article name field and it will work correctly.

**Comment by ShimolinNik** [comment]
But if I put bytes32, I can only safe 32 bytes => 32 characters?
If I want to safe more, how should I do? 
Could you help me please?

**Comment by ShimolinNik** [comment]
I have another error now :) Contract deployment errorError: Returned error: exceeds block gas limit

**Comment by petrosDemetrakopoulos** [comment]
To tackle with the second error, you should launch ganache with increased block gas limit and initial amount on the wallet.
This can be done with the following command:

`ganache-cli -e 80000000000000 -l 80000000000000`

-e parameter is the initial amount of ether in the wallet
-l parameter is the gas limit

**Comment by petrosDemetrakopoulos** [comment]
Regarding the bytes32 issue, unfortunately, Solidity only supports currently up to 32 bytes per variable so storing a larger string in one variable is not possible. Probably you could handle the issue by declaring more than one field where the comment will be stored and concatenate them in the API or front-end side of your project.

**Comment by ShimolinNik** [comment]
Ooook, thanks a lot

**Comment by ShimolinNik** [comment]
Can You look please at my new problem?
Is this a good body for new block? When I have /create command
{articleName:'Something', articleText: 'hashofthisText', comment: 'The first one'}

**Comment by petrosDemetrakopoulos** [comment]
Yes, it looks ok. 
Please star https://github.com/petrosDemetrakopoulos/ethairballoons-CRUD-API and https://github.com/petrosDemetrakopoulos/ethairballoons repos if you found the library useful.

**Comment by ShimolinNik** [comment]
Yeah, of corse
